create table skills (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    display_name varchar(80) not null
);

create table employees (
    id bigint generated by default as identity primary key,
    full_name varchar(120) not null,
    team_name varchar(80) not null,
    max_weekly_hours integer not null,
    preferred_shift_type varchar(20) not null
);

create table employee_skills (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    skill_id bigint not null,
    skill_level integer not null,
    constraint fk_employee_skills_employee foreign key (employee_id) references employees(id),
    constraint fk_employee_skills_skill foreign key (skill_id) references skills(id),
    constraint uq_employee_skill unique (employee_id, skill_id)
);

create table availability_windows (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    day_of_week varchar(16) not null,
    start_time time not null,
    end_time time not null,
    constraint fk_availability_employee foreign key (employee_id) references employees(id)
);

create table shifts (
    id bigint generated by default as identity primary key,
    shift_date date not null,
    start_time time not null,
    end_time time not null,
    shift_type varchar(20) not null,
    priority varchar(20) not null,
    location varchar(80) not null,
    required_skill_id bigint not null,
    required_headcount integer not null,
    notes varchar(255),
    constraint fk_shift_required_skill foreign key (required_skill_id) references skills(id)
);

create table shift_assignments (
    id bigint generated by default as identity primary key,
    shift_id bigint not null,
    employee_id bigint not null,
    assigned_at timestamp not null,
    constraint fk_assignment_shift foreign key (shift_id) references shifts(id),
    constraint fk_assignment_employee foreign key (employee_id) references employees(id),
    constraint uq_assignment unique (shift_id, employee_id)
);
